### ISSUE TITLE
Entering a repository name always fails

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-weblint#15]
**STR:**
1. Visit http://lint.travis-ci.org/
2. Enter `travis-ci/travis-yaml` in the field that says "enter your github repository"
3. Press submit

**Expected:**
Lint results shown, or at the very least an informative error message.

**Actual:**
"failed to fetch .travis.yml"
...with the GET to http://lint.travis-ci.org/travis-ci/travis-yaml returning a HTTP 400.

**Comment by backspace** [comment]
hmm, this is working for me now. I’m going to close this, hopefully it was a temporary problem?
